config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  with_options(defaults: { format: :json }) do |actions|
    actions.get('seller_names', to: 'sellers#index')
    actions.get('guest_names', to: 'guests#index')
    actions.get('sponsor_names', to: 'sponsors#index')
  end

  scope(':locale') do
    devise_for(:users)

    with_options(
      only: %i(index new create edit update),
    ) do |actions|
      resources(:lotteries, only: %i(index new create edit show update)) do
        actions.resources(:prizes)
        actions.resources(:tickets)
        resources(:tables, only: %i(index new create edit show update))
        resources(:ticket_registrations, only: %i(index edit update))
        resources(:ticket_impressions, only: %i(index show))
        resources(:ticket_drop_offs, only: %i(index update))
        resources(:ticket_draws, only: %i(index update))
        resources(:drawn_tickets, only: %i(index update))
        resources(:results, only: :index)
        resources(:results_dashboards, only: :index)
        resource :tickets_dashboard, only: :show
      end
      actions.resources(:sellers)
      actions.resources(:guests)
      actions.resources(:sponsors)
      actions.resources(:users)
    end
    resources(:lock_lotteries, only: :update)

    root 'lotteries#index'
  end

  mount(ActionCable.server => '/cable')
end

app/models/lottery.rb
# frozen_string_literal: true
class Lottery < ApplicationRecord
  has_many :prizes
  has_many :tables
  has_many :tickets

  validates :event_date, presence: true
  validates(
    :ticket_price,
    :meal_voucher_price,
    numericality: { greater_than: 0, less_than: 10_000 },
    allow_nil: true,
  )

  def create_ticket(attributes = {})
    number = attributes.fetch(:number) { next_ticket_number }
    tickets.create!(
      number: number,
      state: 'reserved',
      ticket_type: 'meal_and_lottery',
      **attributes,
    )
  end

  def registerable_tickets
    tickets.where(registered: false)
      .where.not(state: 'reserved')
  end

  def printable_tickets
    tickets.where(
      ticket_type: 'meal_and_lottery',
      registered: true,
    )
  end

  def droppable_tickets
    tickets.where(
      registered: true,
      dropped_off: false,
    )
  end

  def drawable_tickets
    tickets.where(
      dropped_off: true,
      drawn_position: nil,
    )
  end

  def drawn_tickets
    tickets.where.not(drawn_position: nil)
  end

  def last_drawn_ticket
    drawn_tickets.order(:drawn_position).last
  end

  def draw(ticket:)
    raise(ArgumentError, 'Ticket has already been drawn') if ticket.drawn_position.present?

    Ticket.transaction do
      drawn_position = next_drawn_position
      assign_prize_to_ticket(drawn_position: drawn_position, ticket: ticket)
      ticket.update!(drawn_position: drawn_position)
    end
    DrawnTicketBroadcastJob.perform_later(lottery_id: id)

    true
  end

  def next_prize_amount
    next_prize = prize(next_drawn_position)
    next_prize&.amount
  end

  def return_last_drawn_ticket
    ticket = last_drawn_ticket
    raise ArgumentError.new(message: 'The lottery contains no drawn tickets') unless ticket

    prize = prizes.find_by(ticket_id: ticket.id)

    Ticket.transaction do
      prize&.update!(ticket_id: nil)
      ticket.update!(drawn_position: nil)
    end

    DrawnTicketBroadcastJob.perform_later(lottery_id: id)

    true
  end

  private

  def next_drawn_position
    drawn_position = last_drawn_ticket&.drawn_position
    drawn_position ||= 0
    drawn_position + 1
  end

  def next_ticket_number
    number = tickets.order(:number).last&.number
    number ||= 0
    number + 1
  end

  def assign_prize_to_ticket(drawn_position:, ticket:)
    selected_prize = prize(drawn_position)
    return unless selected_prize

    selected_prize.update!(ticket: ticket)
  end

  def prize(position)
    nth_before_last = if position == 1
      nil
    else
      tickets.where(dropped_off: true).count - position
    end

    prizes.find_by(nth_before_last: nth_before_last)
  end
end

app/controllers/lotteries_controller.rb
# frozen_string_literal: true

class LotteriesController < ApplicationController
  def index
    @lotteries = Lottery.order(event_date: :desc)
  end

  def new
    @lottery = Lottery.new
  end

  def create
    @lottery = Lottery.new(lottery_params)
    return(redirect_to(lotteries_path)) if @lottery.save
    render(:new)
  end

  def show
    find_lottery
    @tickets_dashboard = TicketsDashboard.new(lottery: @lottery)
  end

  def edit
    find_lottery
  end

  def update
    find_lottery
    return(redirect_to(lotteries_path)) if @lottery.update(lottery_params)
    render(:edit)
  end

  private

  def find_lottery
    @lottery = Lottery.find(params[:id])
  end

  def lottery_params
    params.require(:lottery)
      .permit(:event_date, :meal_voucher_price, :ticket_price)
  end
end

app/helpers/lotteries_helper.rb
# frozen_string_literal: true

module LotteriesHelper
  def lock_or_unlock(lottery)
    action = if lottery.locked?
      'unlock'
    else
      'lock'
    end

    t(format('helpers.submit.lock_lotteries.update.%s', action))
  end
end

app/views/lotteries/_form.html.erb
<%= form_for(@lottery, html: { class: 'form-horizontal lottery' }) do |f| %>
  <% if @lottery.errors.any? %>
    <div id='error_expl' class='panel panel-danger'>
      <div class='panel-heading'>
        <h3 class='panel-title'><%= t(
          'activerecord.errors.models.lottery.errors.header',
          count: @lottery.errors.count,
          model: Lottery.model_name.human.downcase,
          default: :'activerecord.errors.template.header',
        ) %></h3>
      </div>
      <div class='panel-body'>
        <ul>
        <% @lottery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label(:event_date, class: 'control-label col-lg-2') %>
    <div class='col-lg-10'>
      <%= f.date_field(:event_date, class: 'form-control', autofocus: true) %>
      <%= f.error_span(:event_date) %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label(:meal_voucher_price, class: 'control-label col-lg-2') %>
    <div class='col-lg-10'>
      <%= f.text_field(:meal_voucher_price, class: 'form-control') %>
      <%= f.error_span(:meal_voucher_price) %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label(:ticket_price, class: 'control-label col-lg-2') %>
    <div class='col-lg-10'>
      <%= f.text_field(:ticket_price, class: 'form-control') %>
      <%= f.error_span(:ticket_price) %>
    </div>
  </div>

  <div class='form-group'>
    <div class='col-lg-offset-2 col-lg-10'>
      <%= f.submit(nil, class: 'btn btn-primary') %>
      <%= link_to(
        t('.cancel', default: t('helpers.links.cancel')),
        lotteries_path,
        class: 'btn btn-default',
      ) %>
    </div>
  </div>
<% end %>

app/views/lotteries/_sidebar.html.erb
<ul class='nav nav-sidebar'>
  <%= menu_item(
    t('results_dashboards.index.title.ordered_by_drawn_position'),
    lottery_results_dashboards_path(@lottery, order_by: :drawn_position),
  ) %>
  <%= menu_item(
    t('results_dashboards.index.title.ordered_by_number'),
    lottery_results_dashboards_path(@lottery, order_by: :number),
  ) %>
  <%= menu_item(
    t('results.index.title'),
    lottery_results_path(@lottery),
  ) %>
  <%= menu_item(
    t('drawn_tickets.index.title'),
    lottery_drawn_tickets_path(@lottery),
  ) %>
  <%= menu_item(
    t('ticket_draws.index.title'),
    lottery_ticket_draws_path(@lottery),
  ) %>
  <%= menu_item(
    t('ticket_drop_offs.index.title'),
    lottery_ticket_drop_offs_path(@lottery),
  ) %>
  <%= menu_item(
    t('ticket_impressions.index.title'),
    lottery_ticket_impressions_path(@lottery),
  ) %>
  <%= menu_item(
    t('ticket_registrations.index.title'),
    lottery_ticket_registrations_path(@lottery),
  ) %>
  <%= menu_item(Ticket.model_name.human.pluralize, lottery_tickets_path(@lottery)) %>
  <%= menu_item(Table.model_name.human.pluralize, lottery_tables_path(@lottery)) %>
  <%= menu_item(Prize.model_name.human.pluralize(I18n.locale), lottery_prizes_path(@lottery)) %>
</ul>

app/views/lotteries/edit.html.erb
<%- model_class = Lottery -%>
<div class='page-header'>
  <h1><%= t(
    '.title',
    default: [:'helpers.titles.edit', 'Edit %{model}'],
    model: model_class.model_name.human.downcase,
  ) %></h1>
</div>
<%= render(partial: 'form') %>

app/views/lotteries/index.html.erb
<%- model_class = Lottery -%>
<div class='page-header'>
  <div class='row-fluid'>
    <h1>
      <%= t(
        '.title',
        default: model_class.model_name.human.pluralize.titleize,
      ) %>
      <div class='pull-right'>
        <%= link_to(
          t(
            'lottery.new.title',
            default: [:'helpers.titles.new', 'New %{model}'],
            model: model_class.model_name.human.downcase,
          ),
          new_lottery_path,
          class: 'btn btn-primary',
        ) %>
      </div>
    </h1>
  </div>
</div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t('column_names.lottery.event_date') %></th>
      <th><%= t('column_names.lottery.meal_voucher_price') %></th>
      <th><%= t('column_names.lottery.ticket_price') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @lotteries.each do |lottery| %>
      <tr>
        <td><%= link_to(lottery.event_date, lottery_tickets_path(lottery)) %></td>
        <td><%= number_to_currency(lottery.meal_voucher_price) %></td>
        <td><%= number_to_currency(lottery.ticket_price) %></td>
        <td>
          <%= link_to(
            t('.edit', default: t('helpers.links.edit')),
            edit_lottery_path(lottery),
            class: 'btn btn-default btn-xs',
          ) %>
          <%= link_to(
            t('.show', default: t('helpers.links.show')),
            lottery_path(lottery),
            class: 'btn btn-default btn-xs',
          ) %>
          <%= link_to(
            lock_or_unlock(lottery),
            lock_lottery_path(lottery),
            method: :patch,
            class: 'btn btn-danger btn-xs',
          ) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lotteries/lottery_child_index.html.erb
<div class='row'>
  <div class='col-sm-2 sidebar'>
    <%= render 'lotteries/sidebar' %>
  </div>
  <div class='col-sm-10 col-sm-offset-2 main'>
    <%= render main_header, **main_header_locals %>
    <%= render main_partial, **main_partial_locals %>
  </div>
</div>

app/views/lotteries/new.html.erb
<%- model_class = Lottery -%>
<div class='page-header'>
  <h1><%= t(
    '.title',
    default: [:'helpers.titles.new', 'New %{model}'],
    model: model_class.model_name.human.downcase,
  ) %></h1>
</div>
<%= render(partial: 'form') %>

app/views/lotteries/show.html.erb
<%- model_class = Lottery -%>
<div class='page-header'>
  <h1><%= t('.title', default: model_class.model_name.human.titleize) %></h1>
</div>

<dl class='dl-horizontal'>
  <dt><strong><%= t('column_names.lottery.event_date') %>:</strong></dt>
  <dd><%= @lottery.event_date %></dd>
</dl>

<%= render partial: 'tickets_dashboards/tickets_dashboard' %>

<%= link_to(
  t('.back', default: t('helpers.links.back')),
  lotteries_path,
  class: 'btn btn-default',
)  %>
<%= link_to(
  t('.edit', default: t('helpers.links.edit')),
  edit_lottery_path(@lottery),
  class: 'btn btn-default',
) %>
<%= link_to(
  lock_or_unlock(@lottery),
  lock_lottery_path(@lottery),
  method: :patch,
  class: 'btn btn-danger',
) %>